shun-osugi/MobileAGroupC

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java
- #36 とりあえず忙しさの表示をできるようにする
- x
- CalenderActivityのみ
- x
- update/#36_ViewBusyはテストBranchのため、今回のプルリクで閉じる
=> [update] #36 prefDataStoreを使わない、当日の忙しさのみを表示

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java
- #2 セルの高さをボタンの有無にかかわらず等しくなるように変更
- セル(linearLayout)の高さを画面全体の高さからヘッダー等を除いた高さを等分した高さに固定
- x
- x
- ボタンが複数個ある際の挙動は未確認
=> [fix] #2 セルの高さを統一

app/src/main/AndroidManifest.xml, app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java, app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/EditScheduleActivity.java, app/src/main/res/drawable/ic_cancel.xml, app/src/main/res/drawable/ic_delete.xml, app/src/main/res/drawable/ic_edit.xml, app/src/main/res/layout/dialog_detail_layout.xml
- #48 予定詳細表示の実装
- ボタンを押した際に、詳細を表示したダイアログが開き、予定の編集、削除、ダイアログを閉じる、ボタンを搭載
- 編集ボタンは新規作成したEditScheduleActivityへ遷移→内容は未実装（AddScheduleActivityとほぼ同一）
- 削除ボタンは押すと確認ダイアログが開き、データベースから予定を削除可能
- EditScheduleActivityは、activity_add_schedule.xmlを使用しています。変更を加えるとこちらも変更されるため、注意が必要。
- x
- x
=> [add] #48 予定詳細表示の実装

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/AddScheduleActivity.java, app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java, app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/EditScheduleActivity.java
- #49 1日に複数の予定が登録できるよう変更
- 同日の予定が登録できるようDB構成を変更し、それに応じて、カレンダー表示、予定追加、予定編集のDB接続部分も修正
- DBは、ユーザ名をなくし、日にちの下に用意した、一意のIDを持ったドキュメント内で管理
- {年(collection)}＞{月(document)}＞{日(collection)}＞{ドキュメントID(document)}＞field(これまで同様)
- DB構成を変更しているため、DB接続部分各所に影響が出ると思われます。
- これまでに登録したデータに干渉することはないため、今までのプログラムを動かす分には問題ないと思います。
- DBの更新は変更内容の通り
- DB構成の変更に注意
=> [add] #49 同日に予定を追加可能にDBを変更

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java
- #50 カレンダーと月表示のずれを直す
- OnResumeでヘッダーの月表示を現在の月にリセットするよう変更
=> [change] #50 OnResumeでヘッダーの月表示を現在の月にリセット

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/AddScheduleActivity.java, app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/EditScheduleActivity.java, app/src/main/res/layout/activity_add_schedule.xml
- 予定通過する沖の画面を編集
- 追加ボタンの位置変更
- 日付の位置変更(時刻の隣に日付の欄を移動、終了時刻の隣にある日付の欄は自動入力される)
- 強度と繰り返しのドロップダウンをドラムロールに変更
- AddScheduleActivityのintensityとanswerの値のコードを変更
- EditScheduleActivityのinitialIntensityとinitialRepeatに値をセットするコードを変更
- 特になし
=> [update] #59 予定追加するときの画面を編集

app/src/main/java/io/github/shun/osugi/busible/dao/DateDao.java, app/src/main/java/io/github/shun/osugi/busible/dao/ScheduleDao.java, app/src/main/java/io/github/shun/osugi/busible/entity/Schedule.java, app/src/main/java/io/github/shun/osugi/busible/repository/ScheduleRepository.java, app/src/main/java/io/github/shun/osugi/busible/ui/Activity.java, app/src/main/java/io/github/shun/osugi/busible/ui/AddScheduleActivity.java, app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java, app/src/main/java/io/github/shun/osugi/busible/ui/EditScheduleActivity.java, app/src/main/java/io/github/shun/osugi/busible/viewmodel/DateViewModel.java, app/src/main/java/io/github/shun/osugi/busible/viewmodel/ScheduleViewModel.java
- #61 SQLiteへの移行
- Scheduleエンティティに外部キーdateIdを導入、一つのDateに複数のScheduleを紐づけ
- Date,ScheduleともにDao,ViewModelに複数の関数を追加
- CalendarActivity,AddScheduleActivity,EditScheduleActivityをSQLiteに対応
- DaoやViewModelに変更を加えているため、各所影響が出ることが予想される。
- x
- EditScheduleActivityについて、データ更新は現状うまくいっていない。
- AddScheduleActivityと比べて、未実装部分が見られたため、EditScheduleActivityにも同じように記述しておいたが、それが原因かは不明。
- Firebase等の元々あった不要なプログラムは一旦全てコメントアウトで残している。
=> [change] #61 SQLiteへの移行（データベース大幅改変）

app/src/main/java/io/github/shun/osugi/busible/ui/AddScheduleActivity.java, app/src/main/java/io/github/shun/osugi/busible/viewmodel/DateViewModel.java
- #113 AddScheduleActivity内のgetOrMake関数でInsert処理が非同期に行われていたことにより、dateIDの取得に失敗していた件についての修正
- DateViewModel内のInsert処理に変更を加え、非同期でdateID取得するのを待った上で、IDを返すようにした。
- getOrMake関数内では、Insert処理の戻り値をそのまま返すようにしている。
- DateViewModel内のInsert処理の戻り値を変更しているため、影響が出る可能性があるが、今のところエラーは見られない。
- x
- しばしば、予定が２回重複して追加されることがあるが、追加側のバグか描画側のバグかは不明。ただ、カレンダー描画において、前月のマスに今月の予定が反映されたり強度の反映がうまくいかないことがあったため（どちらも再描画すると改善）、描画処理の見直しは必要と思われる。
=> [fix] #113 DateViewModel内のinsert処理において、非同期処理終了後に日付のIDを返すよう変更

app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java, app/src/main/java/io/github/shun/osugi/busible/ui/EditScheduleActivity.java
- #115 #58 
- AddScheduleActivityを基に一からEditScheduleActivityを作成
- EditScheduleActivityはAddScheduleActivityに倣い、initializeFields関数により、登録された値を各フィールドに設定している
- 変更適用時には、元の予定を削除し、変更後の予定を新たな予定として登録している
- ついでにCalendarActivityからEditScheduleActivityに遷移時にダイアログを消すように変更
- x
- x
- x
=> [fix] #115 予定の変更が適用されるよう修正

app/src/main/java/io/github/shun/osugi/busible/ui/EditScheduleActivity.java
- #115 
- 予定編集時に、元のデータを削除し新たなデータを保存していたのを、元のデータを更新するように変更
- 保存時のデータ削除を削除
- EditScheduleActivity内のsaveSchedule関数をupdateSchedule関数とし、関数内のinsert処理をupdate処理に変更
- 
- x
- x
=> [change] #115 予定変更時の操作を変更

app/src/main/java/io/github/shun/osugi/busible/ui/AddScheduleActivity.java, app/src/main/java/io/github/shun/osugi/busible/ui/EditScheduleActivity.java
- 122
- 予定追加画面で開始時間よりも終了時間が早くても保存できてしまうのを解消するために、開始時間よりも終了時間が早いときには保存ボタンを押せなくし、メッセージを表示させるようにした。
- 特になし
- 特になし
=> [add] #122 予定追加画面で開始時間よりも終了時間が早くても保存できてしまうのを解消

app/src/main/java/io/github/shun/osugi/busible/ui/EditScheduleActivity.java
- 123
- 予定追加画面で予定日を変更したら、デフォルトで変更したその日が選択されているようにした。
- 特になし
- 特になし
=> [fix] #123 予定追加画面で予定日を変更したら,デフォルトで変更したその日が選択されているようにする

app/src/main/java/io/github/shun/osugi/busible/ui/AddScheduleActivity.java, app/src/main/java/io/github/shun/osugi/busible/ui/EditScheduleActivity.java
- 122
- 保存ボタンをおすことで, 
- タイトルが入力されていない時→タイトルを入力してください
- 開始時間より終了時間の方が早い時→開始時間は終了時間よりも前にしてください
- タイトルの入力なしかつ 開始時間より終了時間の方が早い時→タイトルを入力し, 正確な時刻を選択して下さい
- とメッセージを出すように修正
- 特になし
- 特になし
=> [add] #122 予定追加画面で状況に応じたメッセージを表示させる

app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java
- 127
- 予定を削除した後にリロードを行わないと背景の色の反映が行われない問題を解決
- 特になし
- 特になし
- 反映の速度が遅く、一瞬変な挙動あり
=> [fix] #127 予定を削除した後にリロードを行わないと背景の色の反映が行われない問題を解決

app/src/main/java/io/github/shun/osugi/busible/ui/AddScheduleActivity.java, app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java, app/src/main/java/io/github/shun/osugi/busible/ui/EditScheduleActivity.java
- #145 
- 予定追加、編集、削除時にて、画面遷移をするように挙動を変更
- 予定追加、編集画面からカレンダー画面に遷移する際に、そのとき選択された年月のカレンダーを表示するように変更
- カレンダー画面への遷移の際に、選択された年月をIntentに渡すように変更している
- なお、値が指定されていない場合は、現在の年月となる
- 影響範囲参照
- この変更により、予定追加、変更、削除後の二重表示、繰り返しとのviewの競合は解決しているが、繰り返しの予定がある日の全ての予定が繰り返されてしまう問題については、繰り返し予定の表示アルゴリズムの変更が必要だと思われるため、未着手である
=> [fix] #145 予定追加、編集、削除時の挙動を変更

app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java
- #98
- ボトムシートダイアログを表示するボタンを押したときに、予定がある場合のみダイアログを表示するように変更（各日の予定数を参照）
- x
- x
- x
=> 予定のない日にダイアログが表示されないよう修正

app/src/main/java/io/github/shun/osugi/busible/dao/RepeatExclusionDao.java, app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java, app/src/main/java/io/github/shun/osugi/busible/viewmodel/RepeatExclusionViewModel.java
- #98 
- 繰り返しの一部削除に対応
- 繰り返し予定の表示は通常予定の表示時には行わず、開始日含め繰り返し予定の表示時に行うように変更
- 繰り返しの予定を削除した場合には、繰り返し除外データベースに日時を登録することで、表示から除外
- x
- x
- たまに、開始日が表示されないときがある
=> [add] #98 繰り返しの一部削除に対応

app/src/main/java/io/github/shun/osugi/busible/dao/RepeatDao.java, app/src/main/java/io/github/shun/osugi/busible/ui/AddScheduleActivity.java, app/src/main/java/io/github/shun/osugi/busible/ui/EditScheduleActivity.java, app/src/main/java/io/github/shun/osugi/busible/viewmodel/RepeatViewModel.java, app/src/main/res/drawable/check_icon.xml, app/src/main/res/layout/activity_add_schedule.xml
- 159
- 予定編集変更
- 予定背景色の白色を削除
- 予定背景色の選択時のチェックの色を白に変更
- x
- x
- x
=> [fix] #159 予定編集を現在の予定追加に合わせたものとした

app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java
- #166 
- AddSchedule内での範囲外のViewBusy参照を修正
- x
- x
- これで修正されたバグの要因は、カレンダーの初日または最終日に予定が入っていることであるため、もともとのクラッシュ原因がこれに該当しているかは不明
=> [fix] #166 AddScheduleでのViewBusyの呼び出しを修正

app/src/main/java/io/github/shun/osugi/busible/ui/AddScheduleActivity.java, app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java, app/src/main/java/io/github/shun/osugi/busible/ui/EditScheduleActivity.java, app/src/main/java/io/github/shun/osugi/busible/ui/SettingActivity.java, app/src/main/res/layout/activity_setting.xml
- #135 単色モードの追加
- #166 隔週のコメントアウト
- プライバシーポリシーへのリンクの追加
- 設定画面にプライバシーポリシーへのリンクを追加
- 設定画面に単色モードへの切り替えスイッチを追加
- 単色モードかどうかのデータはSharedPreferencesを用いて保存
- ドロップダウン内の隔週をコメントアウト
- 新たに単色モードかどうかのデータをSharedPreferencesを用いて保存するようにしたが、SQLiteの既存データベースには影響はないものと思われる
- x
- x
=> [add] #135 単色モードの追加及びプライバシーポリシーへのリンクの追加、隔週のコメントアウト

app/src/main/java/io/github/shun/osugi/busible/ui/EditScheduleActivity.java
- #159
- 予定編集画面での色の初期選択の表示を実装
- 特になし
- 予定編集画面を開く
- x
=> [fix] #159 予定編集画面での色の初期選択の適用
