shun-osugi/MobileAGroupC

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/MainActivity.java

- データ消した
- データ消した
- 特になし
- 特になし

[add] #1 データ入力1行消した

---

app/build.gradle
app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/MainActivity.java
app/src/main/res/layout/activity_main.xml

- 初期設定変更
- ログイン画面UI追加
- 初期設定変更
- ログイン画面UI追加
- 全体
- もしかしたらsync nowをする必要あるかも
- 即プルしなさい

[add] #1 初期設定の変更

---

.idea/gradle.xml
.idea/misc.xml
app/src/main/res/layout/activity_add_schedule.xml

[add] #3 デザイン作成

---

.idea/misc.xml
app/src/main/AndroidManifest.xml
app/src/main/res/layout/activity_calendar.xml

- #2 フレームの変更
- ヘッダー/フッターをImageViewに
- 特になし
- 特になし
- ほかのViewを追加して最終的な枠組みを整える

[change] #2 ヘッダー/フッターをImageViewに仮変更

---

app/src/main/res/layout/activity_add_schedule.xml

- 3
- 保存ボタンを追加しました
- 特になし
- 特になし

[add] #3 保存ボタンの追加

---

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java
app/src/main/res/layout/activity_calendar.xml

add #2 ボタンを追加

---

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java
app/src/main/res/drawable/ic_add_circle.xml
app/src/main/res/drawable/ic_arrow_back.xml
app/src/main/res/drawable/ic_arrow_forward.xml
app/src/main/res/drawable/ic_circle.xml
app/src/main/res/layout/activity_calendar.xml

- フッターの追加
- フッターのImageButtonを追加
- x
- x
- x

add #2 フッター追加

---

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java

- #2 カレンダー内の日付表示
- 日付表示を作成
- x
- x
- 現在の月を指定した場合に最大日数が今日になることにより、今月を表示させた場合のみ日付がずれるバグあり。

change #2 日付表示

---

app/src/main/res/values/colors.xml

- #2 カラーの追加
- color.xmlを編集
- busyColor7~busyColor0
- x
- x

[Add] #2 カラーの追加

---

app/src/main/AndroidManifest.xml
app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/AddScheduleActivity.java

[add] #3 DB接続

---

app/src/main/res/layout/activity_add_schedule.xml

[add] #3 ヒントを表示する機能追加

---

app/src/main/AndroidManifest.xml
app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/MainActivity.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/values/strings.xml

- ログイン画面完成
- ページ遷移の追加
- 永続化されたデータがあるかのチェック
- アプリ名変更
- なし
- なし

[add] #1 ログイン画面完成

---

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java

change #2 DB接続

---

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/AddScheduleActivity.java
app/src/main/res/layout/activity_add_schedule.xml

[add] #3 詳細の修正

---

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/AddScheduleActivity.java
app/src/main/res/layout/activity_add_schedule.xml

[add] #32 戻るボタンの追加

---

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/AddScheduleActivity.java
app/src/main/res/layout/activity_add_schedule.xml

- 33
- 日付以外の入力ができないようにしました.
- 特になし
- 特になし

[add] #33 日付入力フォームの修正

---

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java
app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/SettingActivity.java
app/src/main/res/layout/activity_setting.xml

- #4 設定画面の追加
- CalendarActivityのImageButtonからSettingActivityに遷移するコードを記述
- SettingActivityに戻るボタンと各曜日のSeekBarを配置
- SeekBarで設定した値を保持する
- 保存した値をカレンダーに反映させる
- x

[add] #4 設定画面の追加

---

app/src/main/res/layout/activity_calendar.xml

- #30 更新時、曜日表示が消える問題を解消
- TableLayoutを曜日表示とカレンダー表示で分離
- カレンダー表示用TableLayoutのIDが従来のTableLayoutのIDになっており、変更の必要性はないと思われる
- x
- x

[fix] #30 更新時、曜日表示が消える問題を解消

---

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java
app/src/main/res/layout/activity_calendar.xml

[fix] #31 ボタンを押下すると、ヘッダーの月が変わる

---

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java

- 31
- 前月・次月の日付をグレーにしました
- 特になし
- 特になし

[update] #31  前月・次月の日付をグレーにする

---

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java

- #31 月移動時、背景色をリセット
- カレンダー再生成時に、背景を白色にリセットするコードを追加
- x
- x
- x

[fix] #31 月移動時、背景色をリセット

---

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java
app/src/main/res/layout/activity_calendar.xml

- #2 カレンダー表示の改善
- 当月以外の日付、予定を正しく反映されるよう変更
- カレンダー描画中に表示されるローディングスピナーを追加、その際、月移動できないよう変更
- 日付の円、日付のテキスト、予定の追加を関数化
- 不要な変数を削除、表示を関数化しているため、影響が出る可能性が有ります。
- x
- 開発時、描画途中に月を変更すると正しく表示されない問題が見られたため、描画中における月移動ボタンの無効化で対処しました。しかし、描画にやや時間がかかるため、操作性に難あり。新たなIssueとして登録して改善を進めます。

[update] #2 カレンダー表示の改善

---

.idea/other.xml
app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java

- #36 color.xmlの変数の反映
- viewBusy関数内の色をbusycolor0~7に紐づけ
- 茶色が出てきていたのもこれのせい

[update] #36 colors.xmlの反映

---

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java

- #36 以前の色の変更が反映されていなかったのを修正
- color.xmlを反映
- 以前は.ideaを編集した?

[update] #36 busyColor反映

---

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java
app/src/main/res/drawable/border0.xml
app/src/main/res/drawable/border1.xml
app/src/main/res/drawable/border2.xml
app/src/main/res/drawable/border3.xml
app/src/main/res/drawable/border4.xml
app/src/main/res/drawable/border5.xml
app/src/main/res/drawable/border6.xml
app/src/main/res/drawable/border7.xml
app/src/main/res/values/colors.xml

- #2 カレンダーに枠線を追加
- 各セルの背景を背景色の指定からリソースの指定に変更。
- 強度に応じて、border[0~7].xmlを参照。
- border[0~7].xml内では、color.xmlを参照している。
- 背景色はcolor.xmlを参照したまま。
- color.xmlに枠線用の色 gray を追加。
- x
- x

[add] #2 カレンダーに枠線を追加

---

.idea/deploymentTargetSelector.xml
.idea/other.xml
app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java

-予定をタップすると表示されるポップアップ内の日付を修正しました 
- 特になし
-特になし
- 特になし

Fix/#31 displayed-num

---

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java

- #65 土日の色付け
- 土曜日の日付を青色、日曜日の日付を赤色に変更
- x
- x
- x

change #65 土日の色付け

---

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java
app/src/main/res/drawable/ic_circle_black.xml
app/src/main/res/drawable/ic_circle_blue.xml
app/src/main/res/drawable/ic_circle_red.xml

- #65 今日の強調表示
- 今日の日付と円の色が反転するように設定
- x
- x
- 日付はテキスト色から、円はdrawableのxmlファイルを指定することで変更

change #65 今日の強調

---

app/src/main/AndroidManifest.xml
app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java
app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/HolidayApiFetcher.java

- 68
- 祝日の導入
- 祝日をapiを叩いて引っ張ってくるようにした
- CalendarActivityいじったけどよほど大丈夫
- アプリを起動すると、logcatに今年の祝日がjson形式で出力される（HolidayApiFetcher
と打つと見つけやすくなる）
- まだ片手落ちです

[add] #68 祝日の取得(json)

---

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java

- #65 今日の表示の修正
- 別月の同じ日も今日と同じ表示になっていたのを修正
- x
- x
- x

fix #65 表示修正

---

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java

- #68 祝日の日付を赤色に変更
- 祝日の日付を赤色に変更
- x
- x
- x

change #68 祝日の日付を赤色に変更

---

app/src/main/java/jp/ac/meijou/s231205036/android/schedulestrengthcalendar/CalendarActivity.java

- #68 別年を取得できるよう変更
- 取得した年を記録し、未取得の年になったときに新たに取得するよう変更
- x
- x
- x

change #68 別年を取得できるよう変更

---

app/build.gradle
app/src/main/java/io/github/shun/osugi/busible/dao/DateDao.java
app/src/main/java/io/github/shun/osugi/busible/entity/Date.java

[add] #61 SQL（ROOM）の使用

---

app/src/main/java/io/github/shun/osugi/busible/database/AppDatabase.java

- 61
- SQLiteのDatabaseの用意
- まだ途中
- sync nowを行う必要あり

[add] #61 SQL（ROOM）でDataBaseを定義

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/github/shun/osugi/busible/model/BusyData.java
app/src/main/java/io/github/shun/osugi/busible/model/HolidayApiFetcher.java
app/src/main/java/io/github/shun/osugi/busible/model/PrefDataStore.java
app/src/main/java/io/github/shun/osugi/busible/ui/AddScheduleActivity.java
app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java
app/src/main/java/io/github/shun/osugi/busible/ui/EditScheduleActivity.java
app/src/main/java/io/github/shun/osugi/busible/ui/MainActivity.java
app/src/main/java/io/github/shun/osugi/busible/ui/SettingActivity.java
app/src/main/res/layout/activity_add_schedule.xml
app/src/main/res/layout/activity_calendar.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_setting.xml
app/src/main/res/layout/dialog_detail_layout.xml

[clean] #78 パッケージの整理

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/github/shun/osugi/busible/entity/Date.java
app/src/main/java/io/github/shun/osugi/busible/ui/DateActivity.java
app/src/main/java/io/github/shun/osugi/busible/viewmodel/DateViewModel.java
app/src/main/res/layout/activity_date.xml

- SQLのDataの追加
- 特になし
- 特になし
- 特になし
- まだ途中

[Add] #61 SQLのDataの追加

---

app/src/main/java/io/github/shun/osugi/busible/dao/DateDao.java
app/src/main/java/io/github/shun/osugi/busible/ui/Activity.java
app/src/main/java/io/github/shun/osugi/busible/ui/DateActivity.java
app/src/main/java/io/github/shun/osugi/busible/viewmodel/DateViewModel.java

- SQLの追加の残り
- とりあえずうまくいったコードです

[add] #61 SQLの追加の残り

---

app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java
app/src/main/res/drawable/ic_home.xml
app/src/main/res/layout/activity_calendar.xml

- #86 ホームボタン作成(今日戻る)
- ホームボタンを設定ボタンの反対側に追加
- 押すとviewがrecreateされる
- 設定ボタンのクリックリスナーが2つあったので片方削除
- x
- x
- x

[Add] #86 ホームボタン実装

---

.idea/deploymentTargetSelector.xml
app/src/main/java/io/github/shun/osugi/busible/model/BusyData.java
app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java
app/src/main/res/drawable/borderx.xml
app/src/main/res/values/colors.xml

- #86 ホームボタン作成
- #36 グレー表示等、細かい修正
- x
- x
- x
- ブランチ名間違えた

Add/#86 ホームボタン実装

---

app/src/main/java/io/github/shun/osugi/busible/dao/DateDao.java
app/src/main/java/io/github/shun/osugi/busible/dao/ScheduleDao.java
app/src/main/java/io/github/shun/osugi/busible/database/AppDatabase.java
app/src/main/java/io/github/shun/osugi/busible/entity/Date.java
app/src/main/java/io/github/shun/osugi/busible/entity/Schedule.java
app/src/main/java/io/github/shun/osugi/busible/ui/AddScheduleActivity.java
app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java
app/src/main/java/io/github/shun/osugi/busible/viewmodel/AddScheduleViewModel.java
app/src/main/java/io/github/shun/osugi/busible/viewmodel/ScheduleViewModel.java

-  AddScheduleActivityにSQL追加
- AddScheduleViewModelの追加
- AddScheduleActivityで入力されるインスタンスをSQLへ保存するためのコードを編集

[add] #61 AddScheduleActivityにSQLを追加

---

app/src/main/java/io/github/shun/osugi/busible/entity/Schedule.java

- 61
- インデックスを追加
- 特になし
- 特になし

[fix] #61 インデックス追加

---

app/src/main/java/io/github/shun/osugi/busible/ui/EditScheduleActivity.java

- #115 
- 「繰り返し」のラベルが違う、強度が+1されてる に対する修正
- x
- x
- x

[fix] #115 予定変更時の表示内容のずれを修正

---

app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java

- #120
- フッター幅をmarginに追加
- x
- x
- x

[fix] #120 最下行がフッターに隠れないように修正

---

app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java

- #93 
- ダイアログ外に触れるとダイアログが閉じるように変更
- ダイアログ内に各予定のメモを表示
- 各予定のタイトル、メモは文字数が多い場合、後ろが省略されるように変更
- x
- x
- x

[change] #93 ダイアログの振舞いを変更

---

app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java
app/src/main/res/values/colors.xml

- #130 
- 入りきらない予定数を白色太字で「＋○」とセル内右下に表示
- addSchduleById内に記述追加
- 視認性向上のため、color.xmlを一部変更
- x
- x
- x

[add] #130 入りきらない予定数の表示を追加

---

.idea/other.xml
app/src/main/java/io/github/shun/osugi/busible/ui/MainActivity.java

- 133
- ログイン画面の削除
- ログイン画面の削除
- 特になし
- アプリを起動する
- 特になし

[remove] #133 ログイン画面削除

---

app/src/main/res/values/colors_mono.xml

- #135
- 単色カラースケールの例(color_mono.xml)の追加
- x
- x
- x

[add] #135 単色カラースケールの例(colors_mono.xml)の追加

---

app/src/main/res/values/colors_mono.xml

Duplicate resourcesエラーの修正
colors.xmlとcolors_mono.xmlで同じcolor nameを使用しているのが原因

colors_mono.xml内のnameを変更

---

app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java

Busyがマイナスの時の表示修正

---

app/src/main/res/drawable/border0_mono.xml
app/src/main/res/drawable/border1.xml
app/src/main/res/drawable/border1_mono.xml
app/src/main/res/drawable/border2.xml
app/src/main/res/drawable/border2_mono.xml
app/src/main/res/drawable/border3.xml
app/src/main/res/drawable/border3_mono.xml
app/src/main/res/drawable/border4.xml
app/src/main/res/drawable/border4_mono.xml
app/src/main/res/drawable/border5.xml
app/src/main/res/drawable/border5_mono.xml
app/src/main/res/drawable/border6.xml
app/src/main/res/drawable/border6_mono.xml
app/src/main/res/drawable/border7.xml
app/src/main/res/drawable/border7_mono.xml
app/src/main/res/drawable/borderx_mono.xml

- 単色バージョンのborder(背景)を追加
- borderにグラデーションを追加
- border〇_mono.xml作成
- [セルの背景色(グラデーション) ]によりグラデーション追加
- border〇.xml内の[セルの背景色][セルの背景色(グラデーション) ]のうち、
下に記述されている方が適応されます
必要ない方を消去してもよい

[add] #135 border変更

---

app/src/main/java/io/github/shun/osugi/busible/ui/SettingActivity.java

- 135
- 単色バージョンの追加によりヘルプボタンの内容を変更
- 特になし
- 特になし

[fix] #135 単色バージョンの追加によりヘルプボタンの内容を変更

---

.idea/other.xml
app/src/main/java/io/github/shun/osugi/busible/dao/RepeatDao.java
app/src/main/java/io/github/shun/osugi/busible/dao/RepeatExclusionDao.java
app/src/main/java/io/github/shun/osugi/busible/database/AppDatabase.java
app/src/main/java/io/github/shun/osugi/busible/entity/Repeat.java
app/src/main/java/io/github/shun/osugi/busible/entity/RepeatExclusion.java

[add] #61 繰り返しテーブルの追加

---

app/src/main/java/io/github/shun/osugi/busible/database/AppDatabase.java

- 61
- DBバージョンの更新
- DBバージョンの更新
- DBのバージョン変更に伴い、DBが再作成されるため、データが全削除されます

[add] #61 DBのバージョン更新

---

app/src/main/java/io/github/shun/osugi/busible/ui/SettingActivity.java

- 135
- 単色バージョンを選んでから前へボタンを押すと次に進んでしまうのを修正
- なし
- なし

[fix] #135 ボタンの修正(前へボタン)

---

.idea/other.xml
app/src/main/java/io/github/shun/osugi/busible/ui/AddScheduleActivity.java
app/src/main/res/drawable/check_icon.xml
app/src/main/res/layout/activity_add_schedule.xml

[add] #58 色の追加

---

app/src/main/java/io/github/shun/osugi/busible/database/AppDatabase.java
app/src/main/java/io/github/shun/osugi/busible/entity/Repeat.java
app/src/main/java/io/github/shun/osugi/busible/ui/AddScheduleActivity.java

- 61
- DBのtableの変更（繰り返し）
- 結構広い
- x
- エラーハンドリングが不十分なので修正します
- 一旦他の部分を進めるための仮の状態です

[fix] #61 DBの変更

---

app/src/main/java/io/github/shun/osugi/busible/dao/ScheduleDao.java
app/src/main/java/io/github/shun/osugi/busible/ui/Activity.java
app/src/main/java/io/github/shun/osugi/busible/ui/AddScheduleActivity.java
app/src/main/java/io/github/shun/osugi/busible/viewmodel/ScheduleViewModel.java

- 61
- DB保存時のエラーハンドリング
- x
- x
- 繰り返し上手に動いてない？

[fix] #61 DBのエラーハンドリング

---

app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java

[clean] #98 繰り返し実装ないしはカレンダーアクティビティの整理

---

app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java

- #98 
- 繰り返し予定追加時に、開始日より後かを判定し、開始日以前（開始日含む）を追加しないように変更
- 予定超過数を表示するテキストの位置、値を修正
- x
- x
- この変更により、開始日以前の予定が表示される問題と開始日が二重になる問題については解決

[fix] #98 開始日以前の繰り返し表示を排除、予定超過数の表示を修正

---

app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java

- #98
- UI表示等をできる限り関数化
- x
- x
- x

[clean] #98 できる限りの関数化

---

app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java

- #130 
- 予定超過数の表示が入りきらなくなっていたので微調整しました
- x
- x
- x

[fix] #130 カレンダー幅調整

---

.idea/other.xml
app/src/main/java/io/github/shun/osugi/busible/dao/ScheduleDao.java
app/src/main/java/io/github/shun/osugi/busible/database/AppDatabase.java
app/src/main/java/io/github/shun/osugi/busible/entity/Schedule.java
app/src/main/java/io/github/shun/osugi/busible/ui/AddScheduleActivity.java
app/src/main/java/io/github/shun/osugi/busible/ui/EditScheduleActivity.java
app/src/main/java/io/github/shun/osugi/busible/viewmodel/ScheduleViewModel.java

- 157
- bool値に変更
- 予定DBの「繰り返し」をBool値に変更
- 読み込むところ
- x
- x

[fix] #157 予定DBの「繰り返し」をBool値に変更

---

app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java

- #98 
- 繰り返しの予定削除時、ダイアログにより、一つだけ削除か全部削除を選べるように変更
- x
- x
- x

[add] #98 繰り返し削除時にすべて削除と一部削除を選べるように変更

---

app/src/main/java/io/github/shun/osugi/busible/ui/AddScheduleActivity.java
app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java
app/src/main/java/io/github/shun/osugi/busible/ui/EditScheduleActivity.java

- #98 
- 編集画面を繰り返しに対応
- 繰り返しあり→あり の場合、repeatTypeが変わらないならupdate、変わるならrepeatを作り直し
- x
- x
- x

[add] #98 編集画面を繰り返しに対応

---

app/src/main/java/io/github/shun/osugi/busible/ui/EditScheduleActivity.java

[add] #122 変更適用

---

app/src/main/java/io/github/shun/osugi/busible/ui/EditScheduleActivity.java

- 159
- 繰り返しの表示ミスの修正
- 特になし
- x
- x

[fix] #159 予定編集で、繰り返しの表示ミスを修正

---

app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java

- #170
- スワイプによる月移動を実装
- x
- x
- カレンダーテーブル内でのみスワイプによる移動が動作するように試行錯誤したが、できてるかあやしい

[add] #170 スワイプによる月移動を実装

---

app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java

- #170 
- スワイプの追加により、ボタンが触れない問題を解消
- 繰り返し予定の削除時のダイアログを一段階減少
- x
- x
- x

[fix] #170 スワイプと削除の修正

---

app/src/main/java/io/github/shun/osugi/busible/ui/CalendarActivity.java

- #173 
- ホームボタンを押したとき、完全にCalendarActivityをやり直す
- ホームボタンのクリックリスナーをrecreateを使用していたのをintentに変更
- x
- overridePendingTransition(0, 0);はアニメーションに関するもの

[fix] #173 ホームボタンの対象月修正

---

app/src/main/res/drawable/border5_mono.xml

- #175 
- border5_mono.xml修正
- x
- x
- x

[fix] #175 border5_mono修正
